name: CI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: deploy pokedex app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: build and deploy web app
      run: |
        npm install
        npm run deploy
