name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    name: deploy pokedex app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: build web app
      run: |
        npm install
        ng build --prod
      
    - name: deploy web app
      uses: JamesIves/github-pages-deploy-action@3.0.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist/pokedex # The folder the action should deploy.
